#!/bin/bash
echo "pre commit hook"
count=`grep -iR 'console\.log' *.js | wc -l | awk '{print $1}'`
if [[ "$count" -ge 2 ]]; then
  echo "    remove any config.log() statements in javascript sources"
  exit 1
fi
